name: excel_reader
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  excel: ^2.0.0-null-safety-3
  file_picker: ^4.5.1
  overlay_support: ^1.2.1
  localstore: ^1.2.3
  android_alarm_manager_plus: ^2.0.5
  flutter_native_timezone: ^2.0.0
  shared_preferences: ^2.0.13
  url_launcher: ^6.1.2

  # rxdart: ^0.27.3
  # flutter_local_notifications: ^9.4.1
  # admob_flutter: ^2.0.0
  # flutter_native_splash: ^2.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/tt.xlsx
    - assets/images/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
